# Generated by Django 5.0.4 on 2024-08-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DGridDesign", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="red",
            name="status",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="status",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
