# Generated by Django 5.1.3 on 2024-12-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0003_linea_i_nodo_v_usuario_redes"),
    ]

    operations = [
        migrations.AddField(
            model_name="linea",
            name="A",
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name="linea",
            name="P",
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name="linea",
            name="Q",
            field=models.TextField(default=0),
        ),
    ]
