# Generated by Django 5.1.1 on 2024-12-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0005_alter_linea_sentido"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutions",
            name="flag_termination_status",
            field=models.IntegerField(
                default=0,
                help_text="Optimal: 1, Unfeasible: 0, Unlimited: 2, NonOptimal: 3",
            ),
        ),
        migrations.AlterField(
            model_name="solutions",
            name="SolverTermination",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="solutions",
            name="status",
            field=models.TextField(),
        ),
    ]
