# Generated by Django 5.1.3 on 2024-12-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0006_solutions_flag_termination_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solutions",
            name="flag_termination_status",
            field=models.BinaryField(
                default=False,
                help_text="Optimal: 1, Unfeasible: 0, Unlimited: 2, NonOptimal: 3",
            ),
        ),
    ]
