# Generated by Django 5.1.3 on 2024-12-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0007_alter_solutions_flag_termination_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solutions",
            name="flag_termination_status",
            field=models.BooleanField(
                default=False,
                help_text="Optimal: Tue, Unfeasible/Unlimited/NonOptimal: False",
            ),
        ),
    ]
