# Generated by Django 5.1.1 on 2024-12-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0008_alter_solutions_flag_termination_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conexiones",
            old_name="idusuario",
            new_name="idUser",
        ),
        migrations.RenameField(
            model_name="red",
            old_name="idusuario",
            new_name="idUser",
        ),
    ]
