# Generated by Django 5.1.1 on 2024-12-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0009_rename_idusuario_conexiones_iduser_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conexiones",
            old_name="idUser",
            new_name="idusuario",
        ),
        migrations.RenameField(
            model_name="red",
            old_name="idUser",
            new_name="idusuario",
        ),
    ]
