# Generated by Django 5.1.1 on 2024-12-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0010_rename_iduser_conexiones_idusuario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conexiones",
            old_name="idusuario",
            new_name="idUser",
        ),
        migrations.RenameField(
            model_name="red",
            old_name="idusuario",
            new_name="idUser",
        ),
    ]
