# Generated by Django 5.1.1 on 2025-01-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0012_linea_zlinep_nodo_zp"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutions",
            name="power_losses",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="linea",
            name="zLinep",
            field=models.TextField(
                default="[]",
                help_text="Existencia del nodo en cada periodo obtenido de la optimizacion",
            ),
        ),
        migrations.AlterField(
            model_name="linea",
            name="zOper",
            field=models.TextField(
                help_text="Existencia del nodo en cada periodo dado por el usuario"
            ),
        ),
        migrations.AlterField(
            model_name="nodo",
            name="zOper",
            field=models.TextField(
                help_text="Existencia del nodo en cada periodo dado por el usuario"
            ),
        ),
        migrations.AlterField(
            model_name="nodo",
            name="zp",
            field=models.TextField(
                default="[]",
                help_text="Existencia del nodo en cada periodo obtenido de la optimizacion",
            ),
        ),
    ]
