# Generated by Django 5.1.1 on 2025-01-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0013_solutions_power_losses_alter_linea_zlinep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="solutions",
            name="PList",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="solutions",
            name="PdgList",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="solutions",
            name="PsList",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="solutions",
            name="QList",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="solutions",
            name="QdgList",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="solutions",
            name="QsList",
            field=models.TextField(default=""),
        ),
    ]
