# Generated by Django 5.1.3 on 2025-01-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "DGridDesign",
            "0015_remove_solutions_plist_remove_solutions_pdglist_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="nodo",
            name="pg",
            field=models.TextField(
                default="", help_text="Potencia Activa de las Generaciones"
            ),
        ),
        migrations.AddField(
            model_name="nodo",
            name="ps",
            field=models.TextField(default="", help_text="Potencia Activa de las Grid"),
        ),
        migrations.AddField(
            model_name="nodo",
            name="qg",
            field=models.TextField(
                default="", help_text="Potencia Reactiva de las Generaciones"
            ),
        ),
        migrations.AddField(
            model_name="nodo",
            name="qs",
            field=models.TextField(
                default="", help_text="Potencia Reactiva de las Grid"
            ),
        ),
        migrations.AlterField(
            model_name="nodo",
            name="p",
            field=models.TextField(help_text="Potencia Activa de las Cargas"),
        ),
        migrations.AlterField(
            model_name="nodo",
            name="q",
            field=models.TextField(help_text="Potencia Reactiva de las Cargas"),
        ),
    ]
