# Generated by Django 5.1.1 on 2025-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0017_linea_ilb_linea_iub_nodo_vlb_nodo_vub"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linea",
            name="ILB",
            field=models.TextField(default="[-500]"),
        ),
        migrations.AlterField(
            model_name="linea",
            name="IUB",
            field=models.TextField(default="[500]"),
        ),
        migrations.AlterField(
            model_name="nodo",
            name="VLB",
            field=models.TextField(default="[10.761]"),
        ),
        migrations.AlterField(
            model_name="nodo",
            name="VUB",
            field=models.TextField(default="[14.559]"),
        ),
    ]
