# Generated by Django 5.1.1 on 2025-02-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0018_alter_linea_ilb_alter_linea_iub_alter_nodo_vlb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameters",
            name="ILBg",
            field=models.FloatField(
                default=-500,
                help_text="Limite inferior global para las corrientes (para todos las lineas y periodos)",
            ),
        ),
        migrations.AddField(
            model_name="parameters",
            name="IUBg",
            field=models.FloatField(
                default=500,
                help_text="Limite superior global para las corrientes (para todas las lineas y periodos)",
            ),
        ),
        migrations.AddField(
            model_name="parameters",
            name="VLBg",
            field=models.FloatField(
                default=0,
                help_text="Limite inferior global para el voltaje (para todos los nodos y periodos)",
            ),
        ),
        migrations.AddField(
            model_name="parameters",
            name="VUBg",
            field=models.FloatField(
                default=5,
                help_text="Limite superior global para el voltaje (para todos los nodos y periodos)",
            ),
        ),
        migrations.AddField(
            model_name="parameters",
            name="maxVLB",
            field=models.CharField(
                default="[0]",
                help_text="Maximo limite inferior de los voltajes en cada periodo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="parameters",
            name="minVUB",
            field=models.CharField(
                default="[5]",
                help_text="Mínimo limite inferior de los voltajes en cada periodo",
                max_length=10,
            ),
        ),
    ]
