# Generated by Django 5.1.3 on 2025-02-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0020_alter_parameters_vnom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameters",
            name="Vnom",
            field=models.CharField(default="[12.66]", max_length=10000),
        ),
        migrations.AlterField(
            model_name="parameters",
            name="maxVLB",
            field=models.CharField(
                default="[0]",
                help_text="Maximo limite inferior de los voltajes en cada periodo",
                max_length=10000,
            ),
        ),
        migrations.AlterField(
            model_name="parameters",
            name="minVUB",
            field=models.CharField(
                default="[5]",
                help_text="Mínimo limite inferior de los voltajes en cada periodo",
                max_length=10000,
            ),
        ),
    ]
