# Generated by Django 5.1.3 on 2025-02-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DGridDesign", "0021_alter_parameters_vnom_alter_parameters_maxvlb_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameters",
            name="PLBg",
            field=models.FloatField(
                default=-100,
                help_text="Limite inferior global para el Potencias activas (para todos los nodos y periodos)",
            ),
        ),
        migrations.AddField(
            model_name="parameters",
            name="PUBg",
            field=models.FloatField(
                default=100,
                help_text="Limite superior global para las Potencias activas (para todos los nodos y periodos)",
            ),
        ),
        migrations.AddField(
            model_name="parameters",
            name="QLBg",
            field=models.FloatField(
                default=-100,
                help_text="Limite inferior global para el Potencias reactiva (para todos los nodos y periodos)",
            ),
        ),
        migrations.AddField(
            model_name="parameters",
            name="QUBg",
            field=models.FloatField(
                default=100,
                help_text="Limite superior global para el Potencias reactiva (para todos los nodos y periodos)",
            ),
        ),
    ]
